### ISSUE TITLE
[BUG] Undefined array key "brokenOrOrphaned"

### ISSUE THREAD

**Issue by ErHaWeb** [CodersCare/transfusion#10]
If I have the situation that two elements in the "Possible Connection" area come into question for an element of the default language and I then delete the element of the default language

![Bildschirmfoto 2024-03-23 um 22 26 43](https://github.com/CodersCare/transfusion/assets/5416710/9605d958-41c8-4549-a29a-b1f4052dbec9)

I get the following php warning when I click on the `Connect` button in the Page Module again:

```
PHP Warning: Undefined array key "brokenOrOrphaned" in /var/www/html/vendor/t3thi/transfusion/Classes/Domain/Repository/TransfusionRepository.php line 204
```

**Comment by Bunnyfield** [comment]
Reverted the latest commit
