### ISSUE TITLE
[BUG] Inappropriate hint when saving

### ISSUE THREAD

**Issue by ErHaWeb** [CodersCare/transfusion#3]
If you select the button `Remove all connection information. Creates an orphaned record!` for a content item in a non-standard language:

![Bildschirmfoto 2024-03-18 um 11 01 10](https://github.com/CodersCare/transfusion/assets/5416710/590492b7-ad85-444d-99f7-6f3ed2a8b64f)

and then click "Save" in the TransFusion Connector, you will be asked:

> **Are you sure you want to remove or delete the marked records?**

This message should only be displayed if content elements have been marked for deletion via the `Delete superfluous record` button.

![Bildschirmfoto 2024-03-18 um 11 01 34](https://github.com/CodersCare/transfusion/assets/5416710/34c3cb00-b2b0-47e9-879c-af725d568d18)

An alternative message could be:
> **Are you sure you want to remove the connections of the selected data records?**

I'm not sure how to handle cases where both the deletion of the element and the deletion of connections elsewhere have been selected. In this case, the message should at least indicate that there is at least one element to be deleted and at least one element whose connection is to be removed.

**Comment by Bunnyfield** [comment]
We can count both of them and come up with a matching message.
