### ISSUE TITLE
[BUG] Mode switch not possible with newly created translation parent

### ISSUE THREAD

**Issue by ErHaWeb** [CodersCare/transfusion#8]
For content elements in the default language that were newly created in the TransFusion Connector using the `Add new translation parent and move to confirmed connections` button, it is not possible to switch back to free mode and then switch back to connected mode, as the reference between the elements is lost when switching to free mode.

**Example:**

In the initial state, we are in free mode in the non-default language. Elements exist here for which no translation parent could be determined in the default language.

![Bildschirmfoto 2024-03-23 um 21 12 54](https://github.com/CodersCare/transfusion/assets/5416710/46a3fa7e-e85e-4337-ba64-b41c55cfd0a9)

By clicking on the `Add new translation parent and move to confirmed connections` button, we indicate that the missing elements should be created in the default language in order to be able to switch to connected mode.

![Bildschirmfoto 2024-03-23 um 21 13 04](https://github.com/CodersCare/transfusion/assets/5416710/6efb487f-74a0-4cc3-9ba1-a9f589592eff)

In the Page module, I now click on the `Disconnect` button in the newly created Connected mode to return to Free mode.

Then I click on the `Connect` button again and notice that the elements that originally belonged together are now displayed separately in the TransFusion Connector. I conclude from this that no connection could be found.

![Bildschirmfoto 2024-03-23 um 21 13 47](https://github.com/CodersCare/transfusion/assets/5416710/5e3a2444-2d71-4f17-9e63-675a3e988576)

I have not yet had a look at the database, but could it be that no corresponding reference is set in the `l10n_source`/`t3_origuid` fields for newly created elements of the default language?

**Comment by Bunnyfield** [comment]
While this might be fixed for the current version, with upcoming CMS 13 compatibility, the field t3_origuid will be removed form the core, so we will need to fall back to other options to determine connections anyway.

Even setting it for the DataHandler does not seem to create a proper value in that field while saving the data.

**Comment by Bunnyfield** [comment]
As a workaround that would be necessary for CMS 13 anyway, there should be a value put in l10n_source instead of t3_origuid, which is then still available after breaking up the connection. This would even be semantically correct, since the source of a connected translation is the original language parent element. So l18n_parent and l10n_source should be the same.
